[project]
name = "resume-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pdfplumber>=0.11.7",
    "pymupdf>=1.26.4",
    "pytesseract>=0.3.13",
    "sentence-transformers>=5.1.0",
    "spacy>=3.8.7",
]
